# Generated by Django 5.2.7 on 2025-10-31 00:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Organization Name')),
                ('code', models.CharField(help_text='Short code (e.g., SPECTRUM, COS)', max_length=20, unique=True, verbose_name='Organization Code')),
                ('department', models.CharField(help_text='e.g., College of Sciences', max_length=100, verbose_name='Department/College')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('booth_location', models.CharField(help_text='e.g., Ground Floor, Main Building', max_length=200, verbose_name='Payment Booth Location')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYearConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20, unique=True, verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer')], max_length=20, verbose_name='Semester')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Period')),
            ],
            options={
                'verbose_name': 'Academic Year Configuration',
                'verbose_name_plural': 'Academic Year Configurations',
                'ordering': ['-start_date'],
                'unique_together': {('academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee/Officer ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('role', models.CharField(help_text='e.g., Treasurer, President, Finance Officer', max_length=50, verbose_name='Role/Position')),
                ('can_process_payments', models.BooleanField(default=True, verbose_name='Can Process Payments')),
                ('can_void_payments', models.BooleanField(default=False, verbose_name='Can Void Payments')),
                ('can_generate_reports', models.BooleanField(default=False, verbose_name='Can Generate Reports')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='paymentorg.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['organization', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(help_text='e.g., Publication Fee, College Fee', max_length=100, verbose_name='Fee Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (₱)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20, verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer'), ('Whole Year', 'Whole Year')], max_length=20, verbose_name='Semester')),
                ('applicable_year_levels', models.CharField(default='All', help_text="e.g., '1,2,3,4' or 'All'", max_length=50, verbose_name='Applicable Year Levels')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Payment Deadline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='paymentorg.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Request ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (₱)')),
                ('queue_number', models.CharField(help_text='e.g., A-042', max_length=10, verbose_name='Queue Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='Status')),
                ('qr_signature', models.CharField(help_text='HMAC signature for validation', max_length=128, verbose_name='QR Signature')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='paymentorg.feetype', verbose_name='Fee Type')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='paymentorg.organization', verbose_name='Organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='paymentorg.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fee Amount (₱)')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Received (₱)')),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Change Given (₱)')),
                ('or_number', models.CharField(max_length=50, unique=True, verbose_name='Official Receipt Number')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOID', 'Void')], default='COMPLETED', max_length=20, verbose_name='Status')),
                ('is_void', models.BooleanField(default=False, verbose_name='Is Void')),
                ('void_reason', models.TextField(blank=True, null=True, verbose_name='Void Reason')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Voided At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paymentorg.feetype', verbose_name='Fee Type')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paymentorg.organization', verbose_name='Organization')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='paymentorg.officer', verbose_name='Processed By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paymentorg.student', verbose_name='Student')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to='paymentorg.officer', verbose_name='Voided By')),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='paymentorg.paymentrequest', verbose_name='Payment Request')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('action', models.CharField(help_text='e.g., PAYMENT_PROCESSED, QR_GENERATED', max_length=50, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='paymentorg.payment', verbose_name='Payment')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='paymentorg.paymentrequest', verbose_name='Payment Request')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('or_number', models.CharField(max_length=50, unique=True, verbose_name='Official Receipt Number')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/pdf/%Y/%m/', verbose_name='Receipt PDF')),
                ('receipt_qr', models.ImageField(blank=True, null=True, upload_to='receipts/qr/%Y/%m/', verbose_name='Receipt QR Code')),
                ('verification_signature', models.CharField(help_text='HMAC signature for receipt verification', max_length=128, verbose_name='Verification Signature')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS Sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='SMS Sent At')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='paymentorg.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['queue_number'], name='paymentorg__queue_n_1c17b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status'], name='paymentorg__status_2f607e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['student', 'status'], name='paymentorg__student_9e733f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['or_number'], name='paymentorg__or_numb_e1f4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student'], name='paymentorg__student_108ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization'], name='paymentorg__organiz_558773_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='paymentorg__status_d0eada_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='paymentorg__created_4554f4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='paymentorg__user_id_6a7910_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='paymentorg__action_659322_idx'),
        ),
    ]
