# Generated by Django 5.2.7 on 2025-11-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0005_college_alter_student_college_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['fee_tier', 'name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='course',
            name='program_type',
            field=models.CharField(choices=[('MEDICAL_BIOLOGY', 'Medical Biology'), ('MARINE_BIOLOGY', 'Marine Biology'), ('COMPUTER_SCIENCE', 'Computer Science'), ('ENVIRONMENTAL_SCIENCE', 'Environmental Science'), ('INFORMATION_TECHNOLOGY', 'Information Technology'), ('OTHER', 'Other')], default='OTHER', help_text='Select the specific program type for fee calculation', max_length=50, verbose_name='Program Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fee_tier',
            field=models.CharField(choices=[('TIER_1', 'Tier 1: Program Affiliation Fees'), ('TIER_2', 'Tier 2: College-Based Organization Fees')], default='TIER_2', help_text='Tier 1: Program-specific fees. Tier 2: College-wide mandatory fees.', max_length=10, verbose_name='Fee Tier'),
        ),
        migrations.AddField(
            model_name='organization',
            name='program_affiliation',
            field=models.CharField(blank=True, choices=[('MEDICAL_BIOLOGY', 'Medical Biology'), ('MARINE_BIOLOGY', 'Marine Biology'), ('COMPUTER_SCIENCE', 'Computer Science'), ('ENVIRONMENTAL_SCIENCE', 'Environmental Science'), ('INFORMATION_TECHNOLOGY', 'Information Technology'), ('ALL', 'All Programs')], default='ALL', help_text='Required for Tier 1 fees. Select the specific program this organization serves.', max_length=50, null=True, verbose_name='Program Affiliation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(help_text='Short code (e.g., CSG, COMPENDIUM, MBIO)', max_length=20, unique=True, verbose_name='Organization Code'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_officer', models.BooleanField(default=False, help_text='Grants officer-exclusive abilities when enabled', verbose_name='Officer Status Flag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
