# Generated by Django 5.2.7 on 2025-10-30 23:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('student_id_number', models.CharField(help_text='University student ID (e.g., 2021-12345)', max_length=20, unique=True, verbose_name='Student ID Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('course', models.CharField(help_text='e.g., BS Biology, BS Computer Science', max_length=100, verbose_name='Course/Program')),
                ('year_level', models.IntegerField(help_text='1, 2, 3, 4, or 5', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Year Level')),
                ('college', models.CharField(default='College of Sciences', max_length=100, verbose_name='College/Department')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text='Format: 09XX-XXX-XXXX', max_length=15, verbose_name='Phone Number')),
                ('academic_year', models.CharField(default='2024-2025', help_text='e.g., 2024-2025', max_length=20, verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer')], default='1st Semester', max_length=20, verbose_name='Current Semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
