# Generated by Django 5.2.7 on 2025-11-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0002_organization_academicyearconfig_officer_feetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_request',
            field=models.OneToOneField(blank=True, help_text='Leave blank for direct payments (not from QR code)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='paymentorg.paymentrequest', verbose_name='Payment Request'),
        ),
    ]
