# Generated by Django 5.2.7 on 2025-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0003_alter_payment_payment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK', 'Bank Transfer')], default='CASH', help_text='Payment method selected by student', max_length=20, verbose_name='Payment Method'),
        ),
    ]
