# Generated by Django 5.2.7 on 2025-11-11 16:26

import django.db.models.deletion
from django.db import migrations, models


def create_default_colleges_and_courses(apps, schema_editor):
    College = apps.get_model('paymentorg', 'College')
    Course = apps.get_model('paymentorg', 'Course')
    
    # Create default college
    default_college, _ = College.objects.get_or_create(
        name='College of Sciences',
        defaults={'code': 'COS', 'description': 'Default college'}
    )
    
    # Create default course
    default_course, _ = Course.objects.get_or_create(
        name='General Studies',
        college=default_college,
        defaults={'code': 'GEN', 'description': 'Default course'}
    )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0004_paymentrequest_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='College/Department Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'College/Department',
                'verbose_name_plural': 'Colleges/Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200, verbose_name='Course/Program Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='paymentorg.college', verbose_name='College/Department')),
            ],
            options={
                'verbose_name': 'Course/Program',
                'verbose_name_plural': 'Courses/Programs',
                'ordering': ['college', 'name'],
                'unique_together': {('name', 'college')},
            },
        ),
        migrations.RunPython(create_default_colleges_and_courses, reverse_migration),
        migrations.AddField(
            model_name='student',
            name='college_fk',
            field=models.ForeignKey(help_text='Select your college/department', null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_temp', to='paymentorg.college', verbose_name='College/Department'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_fk',
            field=models.ForeignKey(help_text='Select your course/program', null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_temp_course', to='paymentorg.course', verbose_name='Course/Program'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: None,  # Populate data if needed
            reverse_migration
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college_fk',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_fk',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(help_text='Select your college/department', null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='paymentorg.college', verbose_name='College/Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(help_text='Select your course/program', null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='paymentorg.course', verbose_name='Course/Program'),
        ),
    ]
