# Generated by Django 5.2.7 on 2025-11-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0006_alter_organization_options_course_program_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.CharField(choices=[('MEDICAL_BIOLOGY', 'Medical Biology'), ('MARINE_BIOLOGY', 'Marine Biology'), ('COMPUTER_SCIENCE', 'Computer Science'), ('ENVIRONMENTAL_SCIENCE', 'Environmental Science'), ('INFORMATION_TECHNOLOGY', 'Information Technology'), ('OTHER', 'Other')], default='MEDICAL_BIOLOGY', help_text='Select one of the 5 supported programs: Medical Biology, Marine Biology, Computer Science, Environmental Science, or Information Technology', max_length=50, verbose_name='Program Type'),
        ),
    ]
