# Generated by Django 5.2.7 on 2025-11-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0007_alter_course_program_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentrequest',
            name='paymentorg__queue_n_1c17b1_idx',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='queue_number',
        ),
    ]
