# Generated by Django 5.2.7 on 2025-11-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0008_remove_queue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Officer who posted this bulk payment request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
    ]
