# Generated by Django 5.2.7 on 2025-11-21 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0009_paymentrequest_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPaymentPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (₱)')),
                ('student_count', models.IntegerField(default=0, verbose_name='Number of Students')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_postings', to='paymentorg.feetype', verbose_name='Fee Type')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_postings', to='paymentorg.organization', verbose_name='Organization')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_fees', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Bulk Payment Posting',
                'verbose_name_plural': 'Bulk Payment Postings',
                'ordering': ['-created_at'],
            },
        ),
    ]
