# Generated by Django 5.2.7 on 2025-11-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0010_bulkpaymentposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from bulk payment posting', null=True, verbose_name='Notes'),
        ),
    ]
