# Generated by Django 5.2.7 on 2025-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0017_remove_officer_can_create_officers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="URL to user's profile picture (from Google or uploaded)", max_length=500, null=True, verbose_name='Profile Picture URL'),
        ),
    ]
